---

- name: Install common vxsuite-complete-system packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ installed_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ removed_packages }}"
