xset -dpms
xset s off
xset s noblank
xrdb ~/.Xresources

export VX_CONFIG_ROOT="/vx/config"
bash /vx/ui/.vx/run-kiosk-browser-forever-and-log.sh &

# brightness all the way
sudo brightnessctl s 100%

exec /usr/bin/openbox-session


