- name: Manage users
  user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment | default('No Comment') }}"
    uid: "{{ item.value.uid }}"
    group: "{{ item.value.primary_group | default(item.key) }}"
    groups: "{{ item.value.secondary_groups | default('') }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
    home: "{{ item.value.home }}"
  with_dict:
    - "{{ users }}"
